apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spark-web-proxy.fullname" . }}
  labels:
    {{- include "spark-web-proxy.labels" . | nindent 4 }}
data:
  config.yaml: |-
    {{ .Values.configuration | toYaml | nindent 4 }}

