image:
  repository: quay.io/okdp/spark-web-proxy
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.1.0"

configuration:
  spark:
    history:
      service: spark-history-server.spark.svc.cluster.local
    ui:
      # -- Specify the base path for the Spark UI proxy.
      # -- When the proxyBase is set to /proxy, enable the property `spark.ui.reverseProxy=true` in your Spark job configuration.
      # -- When the proxyBase is set to a value other than `/proxy`, disable the property `spark.ui.reverseProxy=false` in your Spark job configuration if already set.
      proxyBase: /sparkui
    jobNamespaces:
    - spark

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: spark-web-proxy.okdp.sandbox
      paths:
        - path: /
          pathType: Prefix

