{{- if .Values.rbac.create -}}
{{- range $jobNamespace := .Values.configuration.spark.jobNamespaces | default list }}
{{- if ne $jobNamespace "" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "spark-history-web-proxy.fullname" $ }}
  namespace: {{ $jobNamespace }}
  {{- with $.Values.rbac.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "spark-history-web-proxy.labels" $ | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: 
    - "pods"
    verbs: 
    - "list"
    - "watch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "spark-history-web-proxy.fullname" $ }}
  namespace: {{ $jobNamespace }}
  {{- with $.Values.rbac.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "spark-history-web-proxy.labels" $ | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "spark-history-web-proxy.serviceAccountName" $ }}
    namespace: {{ $.Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "spark-history-web-proxy.fullname" $ }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
{{- end }}
